### ISSUE TITLE
UI 피드백 반영

### ISSUE THREAD

**Issue by imhjnoh** [extreme-todo/frontend#122]
깨지는 UI 확인도 함께 진행
- [-] 3번째 페이지 줄이면 크기 이상함 마진때문인거같음 -> dvh 변경으로 해결
- [x] MainTodoContainer 필요 없을 것 같다.
- [-] 줄이면 사이즈가 초과 됨 -> dvh 변경으로 해결
- [-] 갭이 크면 2페이지꺼가 튀어나온다 -> dvh 변경으로 해결
- [x] 세팅모달 useState 필요없는 것 같다

**Comment by ferrariRoma** [comment]
- 혹시.. currentTodo 없을 때 reset 동작  안 하게는 안 되겠죠?
- 무언가 100프로가 넘으면 퍼센트가 안 차는 건 안 되나요? 꿀밤 때리셔도 좋습니다 허허 :)

**Comment by imhjnoh** [comment]
> * 혹시.. currentTodo 없을 때 reset 동작  안 하게는 안 되겠죠?
> * 무언가 100프로가 넘으면 퍼센트가 안 차는 건 안 되나요? 꿀밤 때리셔도 좋습니다 허허 :)

1번 의견 바로 반영하겠습니다!
2번은 구두로 말씀드린 것처럼 얼마나 신나게 쉬었는지.. 알려주기 위해서 그렇게 설정했던 거라서 그대로 가기로 했습니다~
