### ISSUE TITLE
배포 후 찾은 hot fix 해야 될 내용들

### ISSUE THREAD

**Issue by ferrariRoma** [extreme-todo/frontend#159]
# update time 메소드 문제
- updateFocusTime이 언제 작동하는지 잘 모르겠습니다. 로그나 백엔드 코드를 보기엔 Cron으로 서버 시간을 기준으로 새벽 5시에 업데이트가 되고 있는데, 사용자의 시간에서 보면 새벽 5시가 아닌 시간에 업데이트가 되고 있는 거 같습니다. 지난 번에 Cron을 걷어낼 때 작업이 누락된 거 같습니다. time 업데이트도, todo 삭제도 '해당 유저가 그날 최초 접속한 처음 1회에 한 해서 진행될 수 있게' 설계하든지, 무언가 사용자의 시간에 맞게 업데이트 하도록 수정되어야 할 거 같습니다.
- 위와 같은 경우에는 만약 해당 유저가 몇 주, 몇 달 동안 접속을 안하다가 했을 때는 문제가 없는지 코드를 확인해야 할 거 같습니다.

# 나의 집중 기록 UI 깨짐
<img width="583" alt="image" src="https://github.com/user-attachments/assets/70f69fd1-2040-4181-b6e8-d7bbd2fa8adb">

# extremeMode와 관련해서(새로고침 하면 current todo가 사라지는 문제)
- 일단 useExtremeMode에서 setMode의 초기화나 수정을 위해서 setting api가 호출되고 있지 않습니다. 그래서 MainTodo에서 익스트림 모드를 온오프 하는 것이 서버로 반영되고 있지 않습니다. 그래서 setting.tsx를 열었을 때 이에 대한 미스매치도 일어나고 있습니다.
  1. MainTodo에서 익스트림 모드를 조작함 -> 로컬 스토리지만 변경
  2. Setting 모달을 엶 -> 서버 데이터와 로컬 스토리지의 불일치
  3. MainTodo로 돌아가면 익스트림 모드가 서버 데이터에 맞춰져 있음 -> 사용자 의도와는 관련 없음

- 이렇게 되면 굳이 setExtremeMode를 state로 설정하지 않아도 되지 않는 것도 고려해 보면 좋을 거 같습니다.
  - 이 부분에 대한 발견을 Setting.tsx에서 setting api를  호출하는 과정에서 useQuery를 사용하지 않은 것을 발견해서 본 김에 리팩토링을 하려고 했는데, useQuery의 OnSuccess와 같은 콜백이 모두 deprecated예정이더라고요. 그래서 이에 대해서 [이 글](https://velog.io/@cnsrn1874/breaking-react-querys-api-on-purpose)을 읽다보니 [이 부분](https://velog.io/@cnsrn1874/breaking-react-querys-api-on-purpose#%EC%B6%94%EA%B0%80-%EB%A0%8C%EB%8D%94%EB%A7%81-%EC%82%AC%EC%9D%B4%ED%81%B4)에서 아차 싶었습니다.
  - 왜냐하면 당연한 부분인데 저희 코드에서 생각보다 서버 데이터를 구태여 상태로 다시 처리하고 있는 부분들이 꽤 많았던 거 같았기 때문입니다.
  - useExtremeMode도 해당하는 것 같아 보이기도 해서 굳이 서버나 로컬 스토리지에 데이터가 있는데 이를 다시금 상태로 처리하는 것을 걷어내면 어떨까 싶습니다. 굳이 상태로 한 번 더 처리를 해서 사용하다 보니 코드의 복잡도가 더 생기고, 희정님도 모르게 이렇게 코드가 흘러간 거 같아서요! 하지만 사용자와 Interaction하는 부분이기도 해서 어쩔 수 없나 싶기도 합니다. optimistic update도 머리에 떠오르긴 합니다.
- 추가적으로 reset이 되는 로직 자체도 조금 더 손볼 필요가 있어 보입니다. 원인이 extremeMode에 대한 서버 데이터와 로컬 상태 간의 불일치이긴 하지만, 표면적으로 드러난 리셋의 루틴도 수상하게 느껴졌기 때문입니다. 
  1. todo에 할 일이 없음
  2. 할 일을 추가함
  3. 이때 쉬는 시간이 초과한 상태면 새로고침 시 reset이 발동함

원래 이 부분을 제가 작업할려고 했는데 생각보다 조금 더 큰 범위에서 고려해야 하는 부분들로 보여서 희정님의 의견도 필요한 거 같습니다! 코멘트 남겨주시면 감사하겠습니다 :)
희정님이 코드랑 이슈 확인하시고 의견 주시면 조율을 해서 작업의 방향성이나 범위를 정하고, 저도 함께 할 수 있는 부분이 있으면 같이 수정해 나가면 될 거 같습니다 😁

**Comment by ferrariRoma** [comment]
이슈를 정리하고서 일단 세번째 익스트림 모드 관련된 문제를 해결해 보려고 하다보니 refreshToken 관련된 이슈('invalid refreshTokens')가 발생했습니다. 제대로 된 해결책을 찾지 못했고, 문득 구글 콘솔에서 프로덕트 모드로 바꿔주지 않아서 그런건가 싶어서 프로덕트 모드로 일단 바꿔주었습니다.
그 뒤로는 reset이 자꾸 작동돼서, focus나 rest의 reset 메소드에서 'db update failed'에러가 발생했습니다. 데이터가 없는데 reset을 요청해서 발생한 에러로 보이더라고요. 그래서 이 부분에 고민을 좀 해보았습니다.

내부적인 로직으로 nextTodo를 추가하는 건 어떨까 하는 생각을 해보았습니다. 아래는 브레인스토밍 하면서 러프하게 정리해 본 내용입니다.

```md
예외1 : todo가 없을 때 초과 되면 호출되면 안 됨.
예외1-1 : 이때 새로운 todo가 추가된다고 해서 초기화 되면 안 됨

예외2 : 

그럼 오히려 반대로 기준을 잡아보자.
1. 진행 중인 todo가 있다. => currentTodo...
nextTodo도 둘까?

(여기서부터 새로운 아이디어에 대한 내용 입니다.)

아래 모든 경우는 익스트림 모드가 true이고 쉬는 시간이 초과됐을 때이다.

case_1 todo가 비었을 때
[]
currentTodo : null
nextTodo : null

reset : X

case_2 빈 todo에 새로운 todo가 추가 됐을 때
[] => [sth]
currentTodo : null
nextTodo : sth

reset : X

'다음 할 일 하기' 누르면
currentTodo : sth
nextTodo : null

reset : O

화면에는 currentTodo.title(todo) || nextTodo.title(todo)로 하면 될 거 같다.
내부적 로직으로 외부엔 드러나는 차이는 없는 것.

case_3 진행 중인 todo가 하나가 있을 때
[sth]

currentTodo : sth
nextTodo : null

reset : O
```

첫 두 개의 케이스에 대해서만 예외처리를 해주면 되기 떄문에 기준이 명확해 지는 것 같더라고요. 따로 reset Flag를 둘 필요도 없어 보이고요. 제가 보기엔 그런데, 제가 작업한 부분이 아니다 보니까 제가 놓친 부분이나 고려하지 못한 부분이 분명히 있을 거 같습니다. 희정님께서 검토하기에도 괜찮으신지 궁금합니다 :)

**Comment by imhjnoh** [comment]
의견 전부 읽어보았습니다! 

1. updateFocusTime 이 백엔드 Timer 서비스에 있는 메소드 말씀하시는 게 맞나요? ('total_focus' patch 엔드포인트) 이 메소드는 Todo 하나를 완료했을 때에만 "나의 집중 기록"에서 조회할 수 있는 시간이 증가하는 로직입니다. Cron과는 관련이 없습니다~

2. 1번에 비롯해서 생각나는 부분으로는 FE와 관련 없이 하루, 일주일, 한 달 단위로 도는 Cron 이 남아있긴 한데요, 이 부분은 사용자의 로컬 시간과는 상관 없이 게임의 랭킹 시스템처럼 일괄 업데이트 되어야 되는 부분이 아닌가 하여 남겨두긴 했었습니다. 동규님의 의견이 궁금합니다!

3. UI이슈 리포트 감사합니다. 조치하겠습니다!

4. 사실 저희가 전체적으로 상태를 많이 사용하게 된 것에는 나름 타당한 히스토리가 있다고 생각하긴 합니다..ㅎㅎ 오프라인을 매우 많이 고려하고 있었어서 Setting도 초기에는 localStorage에 동시에 업데이트를 하고 있었습니다. 현재는 저희 로직에서 오프라인 케이스가 많이 걷어졌으니 충분히 useQuery만을 사용해서 처리해도 된다는 생각이 듭니다~ 적어도 setting 은 업데이트 해도 좋을 것 같습니다👍

5. 의견 감사합니다! 다만 nextTodo와 currentTodo의 역할에 혼란이 올 수는 있다는 우려가 살짝 되네요.. `currentTodo.title(todo) || nextTodo.title(todo)` 이런 지점에서요..! 사용자는 모르지만 유지보수하는 개발자도 이해하기 쉬우면 좋을 것 같은데 이 의견에 착안해서 reset 플래그 대신에 currentTodo가 settled.. 그러니까 지금 언급해주신 nextTodo가 currentTodo로 이동하는 부분을 그냥 boolean 플래그로 사용하면 조금 더 이해가 쉬워지지 않을까..라는 생각이 드는데 어떠신가요?

**Comment by ferrariRoma** [comment]
1. 헉, 제가 잘못 본 거 같습니다. 1번과 관련해서는 2번에서 말해주셨던 Cron을 말하는 것이었습니다. updateDay, Week, Month를 말하는 것이었습니다ㅋㅋㅋ 제가 메소드명을 착각한 거 같습니다. 죄송합니다.
저도 코멘트를 남기고서 지속적으로 고민을 해보았는데, 다음과 같은 문제는 없을지 궁금합니다.

  #### 1. 지난 날짜에 맞게 todo를 지워주는 것처럼 개별 사용자에 맞춰서 update를 해주고, Cron도 살려두는 경우
  현행 메소드가 호출했을 때, thisMonth를 lastMonth로, thisWeek를 lastWeek로 밀어내는 형식이다 보니 중복해서 밀어지게 될 거 같습니다.

  #### 2. 개별 업데이트 없이 Cron을 살려두는 경우(현행 코드)
  현재 저희가 위치한 대한민국을 기준으로 했을 때는 오후 2시에 업데이트가 진행 됩니다. 그 말은 새벽 5시부터 오후 2시까지 9시간 동안 오늘 한 작업이 어제 기록이 되고, 월요일에 한 작업이 지난 주 기록이 되고, 8월 1일에 한 작업이 7월 기록으로 되는거더라고요.

그래서 결론적으로는 `removeTodosBeforeDate` 호출처럼 해야 될 거 같습니다. 살펴본 결과 `removeTodosBeforeDate`도 만들어 져 있지 어디서도 호출은 안 되고 있더라고요. 아직 지난 일자 todo 대한 초기화도 진행되고 있지 않습니다. updateDay,Week,Month와 함께 적용하면 좋을 거 같습니다.

다만, 이렇게 되면 고민이 되는 부분이 앞서 말씀드렸던, 단순히 thisMonth가 lastMonth로 옮겨가는 구조상 2달 뒤에 접속을 해도 thisMonth가 lastMonth로 옮겨지고 끝날 거 같습니다, 2달 전 데이터 임에도 말이죠. 이 부분에 대해서는 조금 대책이 필요할 거 같습니다.

4. 저는 오프라인을 고려해서 원격DB와 함께 todo 도메인에서는 indexedDB로, 나머지 도메인에서는 localStorage를 사용하고 있고, 이 모든것에 일괄적으로 react query를 적용할 수 있기 때문에 유저와의 상호작용에 큰 문제가 없다면 제거할 수 있는 최대한으로 state를 걷어내면 좋지 않을까 했었습니다. 이미 indexedDB, localStorage, mySQL에 데이터를 처리하는데, 이 데이터를 패치 후 state까지 처리해야 한다면 개발하는 입장에서도 고려해야 할 것이 더 많은 것 같습니다.
서버의 데이터를 `서버 state`로써 바로 사용할 수 있는 게 react query라고 생각하는데, 로컬 상태를 중간에 넣게 되면 이 편의성이 줄어들기 때문에 react query를 사용하는 부분에서는 되도록이면 useState를 사용하지 않는 것이 react query를 최대한 활용하는 방법이라고 생각합니다. 둘 다 쓰면 예전에 항해에서 서버 상태는 react query로 받아와서 그걸 다시 redux에 넣어서 로컬 state를 관리하는 것과 비슷한 느낌 같습니다ㅋㅋ

5. 이 부분은 잘 이해가 안 됩니다. settled를 하면 nextTodo의 존재 여부를 처리할 수 있는지 궁금합니다. 이 부분은 미팅에서 조금 더 설명해주시면 좋을 거 같습니다 :)

**Comment by imhjnoh** [comment]
구두로 논의된 내용입니다~
1. `removeTodosBeforeDate`를 추가하겠습니다.
     done이 true인 것 중 3개월치 DB에 남기고 지난달,이번달 등등 계산은 그때그때 계산하도록 
4. 완전히 동의합니다.
5. 일단 오늘 할 todo가 한 개도 없을 경우 타이머가 돌아가지 않도록 조치하겠습니다.

**Comment by ferrariRoma** [comment]
아아 마이크 테스트

**Comment by imhjnoh** [comment]
마이크테스트2

**Comment by imhjnoh** [comment]
- [ ] 메인 투두에서 익스트림 아이콘 클릭시 BE에도 반영
