### ISSUE TITLE
의문의 todolist, ranking에서 초기화 문제

### ISSUE THREAD

**Issue by ferrariRoma** [extreme-todo/frontend#166]
#164 PR을 공유해 주실 때 말씀해 주셨던 왜인지 모르겠지만 todolist와 ranking에서 초기화 문제가 생긴다는 게 왜 그러는지 알 것 같은데 확인 한 번 해주시죠 :)

카톡으로 전달해드린 영상을 참고해주시면, 분명히 익스트림 모드가 false이고 localStorage에서도 false인 걸 확인할 수 있습니다. 하지만 새로고침을 하면 아래 구간(익스트림 모드가 true일 때 동작하는 조건문)이 작동합니다.
https://github.com/extreme-todo/frontend/blob/56291e48bb8e7f1b01155fa500ce0e8a099e31b5/src/hooks/useExtremeMode.tsx#L68-L89

그래서 찾아보니 아래 부분의 `DEFAULT_IS_EXTREME`이 true이기 때문에 최초 렌더링 시 저기를 들리더라고요.
https://github.com/extreme-todo/frontend/blob/56291e48bb8e7f1b01155fa500ce0e8a099e31b5/src/hooks/useExtremeMode.tsx#L96-L100

해당 영상에서는 todo가 아무것도 없어서 위 코드의 나머지 조건문인 `prevStatus.current === status.isResting &&
      resetFlag === false &&
      currentTodo !== null &&
      Number(leftMs) < 0`도 모두 통과한 거 같은데, 왜인지는 모르겠지만 저 상황을 만족하는 특정 상황에서 새로고침을 하면 extremeMode가 false라도 최초에 true이기 때문에 돌아갈 수 있는 거 같습니다.

제가 생각한 해결책으로는 useQuery를 사용함과 동시에 위 코드에 `[extremeMode, setExtremeMode]`를 제거하고 useQuery data 하나로 사용을 하고, leftTime만 상태로 사용하면 어떨까 생각을 해 봅니다. 굳이 왜 `DEFAULT_IS_EXTREME`를 false로 하지 않고 useQuery를 사용할까 하는 의문이 생길 수도 있지만 

https://github.com/extreme-todo/frontend/blob/56291e48bb8e7f1b01155fa500ce0e8a099e31b5/src/hooks/useExtremeMode.tsx#L35-L46

이 부분에서 api 호출 결과에서 설령 에러가 발생한다면 로컬 상태는 업데이트가 되는데, api는 에러가 발생한다면 결과적으로 로컬 상태와 서버 상태의 미스매치가 나게 될 가능성이 있어 보입니다.

의견 편하게 코멘트로 남겨주세요 :)

P.S : 추가적으로 기존 코드의 오류(?)를 발견한 거 같은데, else 문에 브라켓이 없다면 로컬 setState만 focusing 모드일 때 건너띄게 되고 api는 실행 됩니다.

```ts
// 수정 전
  const setMode = (newMode: boolean) => {
    if (status.isFocusing === true) {
      window.alert('집중 시간에는 모드 변경이 불가능합니다.');
    } else
      setExtremeMode((prev: IExtremeMode) => {
        return { ...prev, isExtreme: newMode };
      });
    settingsApi.setSettings({
      extremeMode: newMode,
      colorMode: 'auto',
    });
  };

// 수정 후
  const setMode = (newMode: boolean) => {
    if (status.isFocusing === true) {
      window.alert('집중 시간에는 모드 변경이 불가능합니다.');
    } else {
      setExtremeMode((prev: IExtremeMode) => {
        return { ...prev, isExtreme: newMode };
      });
      settingsApi.setSettings({
        extremeMode: newMode,
        colorMode: 'auto',
      });
    }
  };
```

이렇게 수정해야 하지 않을까 합니다 :)

**Comment by imhjnoh** [comment]
확인이 늦어서 죄송합니다😭
짚어주신 부분 코드 다시 보니 정확한 원인은 currentTodo의 비교연산자가 `!=` 가 아니고 `!==`여서 undefined 일 때도 true가 되었던 것 같습니다.
일단 이 부분을 해결하면 되지 않을까 하네요!
사실 로그인 안 한 유저는 서버와 동기화를 못해서 extremeMode를 사용하지 못하게 되는 점이 걸리는데, 현 시점에서는 로그인 해야만 서비스 이용이 가능하니 useQuery로 변경해도 별 문제는 없어보이긴 합니다.
다만 pomodoro와 extreme로직이 상당히 복잡하고 꼬여있어서..useQuery로 수정했다가 또 다른 이슈가 생기진 않을지 걱정입니다. 차라리 로직 자체를 처음부터 다시 작업하는게 나을 것 같기도 하고요😭😭😭
상세히 봐주셔서 감사합니다! 항상 섬세한 리뷰에 감동입니다.🙇‍♂️🙇‍♂️

바로바로 실행하면서 확인해보려 했는데 집중 모드로 들어가지지 않고 휴식 오버레이가 계속 깜빡거리는 문제가 생겨 확인해보지 못하고 있습니다.. 혹시 동규님 환경에서는 이런 일이 없을까요..? 마지막으로 실행했을 때는 잘 됐던 것 같아서 요상합니다..

**Comment by ferrariRoma** [comment]
> 확인이 늦어서 죄송합니다😭 짚어주신 부분 코드 다시 보니 정확한 원인은 currentTodo의 비교연산자가 `!=` 가 아니고 `!==`여서 undefined 일 때도 true가 되었던 것 같습니다. 일단 이 부분을 해결하면 되지 않을까 하네요! 사실 로그인 안 한 유저는 서버와 동기화를 못해서 extremeMode를 사용하지 못하게 되는 점이 걸리는데, 현 시점에서는 로그인 해야만 서비스 이용이 가능하니 useQuery로 변경해도 별 문제는 없어보이긴 합니다. 다만 pomodoro와 extreme로직이 상당히 복잡하고 꼬여있어서..useQuery로 수정했다가 또 다른 이슈가 생기진 않을지 걱정입니다. 차라리 로직 자체를 처음부터 다시 작업하는게 나을 것 같기도 하고요😭😭😭 상세히 봐주셔서 감사합니다! 항상 섬세한 리뷰에 감동입니다.🙇‍♂️🙇‍♂️

아하, isExtreme이 최초 렌더링 시 true로 되어 있는 건 문제가 아니군요.

> 바로바로 실행하면서 확인해보려 했는데 집중 모드로 들어가지지 않고 휴식 오버레이가 계속 깜빡거리는 문제가 생겨 확인해보지 못하고 있습니다.. 혹시 동규님 환경에서는 이런 일이 없을까요..? 마지막으로 실행했을 때는 잘 됐던 것 같아서 요상합니다..

저도 그 부분을 한 번 만났습니다 ㅠㅠ 놀래서 녹화 해뒀습니다. 근데 그 뒤로는 따로 안 보여서 따로 말씀은 안드렸는데.. 희정님도 발견하셨군요. 말씀주신대로 너무 꼬여있나 싶긴 하달까요. 이것도 이 이슈에서 발생한 무한 렌더링이나 그런 종류의 문제 같아 보여서요ㅋㅋ

**Comment by imhjnoh** [comment]
구두 회의 후 #169 와 같이 반영되었으므로 이슈 닫습니다.
