### ISSUE TITLE
테스트 코드 깨지는 버그 수정

### ISSUE THREAD

**Issue by imhjnoh** [extreme-todo/frontend#95]

**Comment by ferrariRoma** [comment]
[여기서](https://github.com/threepointone/react-act-examples/blob/master/sync.md) 확인했는데, 초기화 버튼이나 회원탈퇴 버튼을 눌렀을 때 handler가 비동기이기 때문에 [이 항목에](https://github.com/threepointone/react-act-examples/blob/master/sync.md#async--await) 해당하더라고요! 그래서 해보니 잘 통과합니다. gpt가 act를 사용하라 해서 act 문서를 보다가 찾게 됐습니다ㅋㅋㅋ
