### ISSUE TITLE
테스트 이슈 수정

### ISSUE THREAD

**Issue by imhjnoh** [extreme-todo/frontend#96]
* [x] 무한 리셋
* [x] 간헐적으로 두 번 둘러야 투두가 완료가 됨
* [x] 랭킹에서 시간 포매팅이 잘 안 됨 ms단위가 아니라 minute인 것 같음.
* [-] 투두 생성했을 때 바로 현재 투두에 반영이 안 됨 -> 이슈 재현 불가능
* [x] 날짜가 의미없이 바로 다음 투두가 시작됨.. 설정된 날짜에 따라 다음 투두를 불러와야 함
* [x] 랭킹 스크롤 짧아지면 어찌할바가 없음
* [x] 투두가 없을 때 휴식으로 카운팅 되도록
* [x] 익스트림 모드 초과, 데이터 초기화 시 todo만 사라짐. ranking 및 focustime 초기화 필요

**Comment by ferrariRoma** [comment]
- [ ] setting modal에서 데이터 초기화 할 때 total_focus_time 초기화 하기
- [ ] `invalidQuery`가 생각한대로 동작하고 있지 않음
	- doTodo 이후에 getList가 다시 호출되고 있지 않음
	- 희정님 하신 테스트 때 발견한 에러 고친 브랜치 PR merge 되면 거기서 이 부분 테스트 해보기
- [ ] NOW에 들어가는 todo(currentTodo) slice하기!
	- currentTodo를 그냥 받아서 NOW에 쓰고, 1번을 slice한다...
	- DnD할 때 방해가 될 수 있는지 확인해보기~
- [ ] addTodo의 submitTodo이 잘 호출되면 add todo modal을 초기화 해주기
- [ ] todoList에 로직 정리하기
